# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build the container
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ./build/subjack-linux-amd64
      - GOOS=darwin GOARCH=amd64 go build -o ./build/subjack-darwin-amd64
